2023-11-23 21:43:49,612 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 21:45:29,487 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 21:45:38,035 django.request WARNING  Not Found: /favicon.ico
2023-11-23 22:02:27,809 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:02:50,476 django.utils.autoreload INFO     C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py changed, reloading.
2023-11-23 22:02:51,357 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:04:57,455 django.utils.autoreload INFO     C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py changed, reloading.
2023-11-23 22:04:58,234 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:09:09,704 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:09:36,453 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:09:42,529 django.utils.autoreload INFO     C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py changed, reloading.
2023-11-23 22:09:43,195 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:11:30,115 django.utils.autoreload INFO     C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py changed, reloading.
2023-11-23 22:11:30,767 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 22:11:58,458 django.utils.autoreload INFO     C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py changed, reloading.
2023-11-23 22:11:59,219 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-23 23:59:46,472 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-24 00:02:52,960 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-24 00:17:14,075 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-24 00:18:25,618 django.request WARNING  Method Not Allowed: /api/user/register
2023-11-24 00:18:54,908 django.request ERROR    Internal Server Error: /api/user/register
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\Python-Test\Test1-Django\users\views.py", line 25, in create
    user = get_user_model().objects.create_user(email=email, password=password, phone_number=phone_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIUserManager.create_user() got an unexpected keyword argument 'email'
